#Defining Custom Network
networks:
  probank-network:
    name: probank-network
    driver: bridge

#Defining Custom Volumes    
volumes:
  probank-database-data:
    name: probank-database-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\DockerVolumes\probank\mysql-data\
      
  probank-backend-data:
    name: probank-backend-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\DockerVolumes\probank\backend-data\

############################### Defining All Services ###############################
services:
  probank-database:
    image: mysql:8.0.36
    container_name: probank-mysql-instance
    networks:
      - probank-network
    ports:
      - 4406:3306
    volumes:
      - probank-database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root #This sets the password of the root user
      MYSQL_DATABASE: probank #This creates the database also when first time instance is created
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s #perform retries in the interval of mentioned time
      timeout: 30s #wait only for mentioned time for the response
      retries: 3 #perform mentioned times retry in case of failure
      start_period: 10s #start health check after mentioned time

  probank-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: probank-rabbitmq-instance
    hostname: rabbitmq
    networks:
      - probank-network
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s #perform retries in the interval of mentioned time
      timeout: 30s #wait only for mentioned time for the response
      retries: 3 #perform mentioned times retry in case of failure
      start_period: 10s #start health check after mentioned time

  probank-eurekaserver: 
    build: probank-eurekaserver/
    image: r15priyanshu/probank-eurekaserver:latest
    restart: always
    container_name: probank-eurekaserver-instance
    networks: 
      - probank-network
    ports:
      - 8761:8761
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-EUREKASERVER
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      probank-database:
        condition: service_healthy

  probank-configserver:
    build: probank-configserver/
    image: r15priyanshu/probank-configserver:latest
    restart: always
    container_name: probank-configserver-instance
    networks: 
      - probank-network
    ports:
      - 8888:8888
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-CONFIGSERVER
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://probank-eurekaserver:8761/eureka/
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      probank-eurekaserver:
        condition: service_healthy


  probank-accounts-service:
    build: probank-accounts-service/ 
    image: r15priyanshu/probank-accounts-service:latest
    restart: always
    container_name: probank-accounts-service-instance
    networks: 
      - probank-network
    ports:
      - 9091:9091
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-ACCOUNTS-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://probank-eurekaserver:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
      SPRING_DATASOURCE_URL: jdbc:mysql://probank-database:3306/probank
      SPRING_RABBITMQ_HOST: probank-rabbitmq
    healthcheck:
      test: "curl --fail --silent localhost:9091/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:  
      probank-configserver:
        condition: service_healthy
      probank-rabbitmq:
        condition: service_healthy
      
    
  probank-loans-service:
    build: probank-loans-service/ 
    image: r15priyanshu/probank-loans-service:latest
    restart: always
    container_name: probank-loans-service-instance
    networks: 
      - probank-network
    ports:
      - 9092:9092
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-LOANS-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://probank-eurekaserver:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
      SPRING_DATASOURCE_URL: jdbc:mysql://probank-database:3306/probank
    healthcheck:
      test: "curl --fail --silent localhost:9092/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      probank-configserver:
        condition: service_healthy


  probank-cards-service:
    build: probank-cards-service/
    image: r15priyanshu/probank-cards-service:latest
    restart: always
    container_name: probank-cards-service-instance
    networks: 
      - probank-network
    ports:
      - 9093:9093
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-CARDS-SERVICE
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://probank-eurekaserver:8761/eureka/
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
      SPRING_DATASOURCE_URL: jdbc:mysql://probank-database:3306/probank
    healthcheck:
      test: "curl --fail --silent localhost:9093/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      probank-configserver:
        condition: service_healthy

  probank-message-service:
    build: probank-message-service/
    image: r15priyanshu/probank-message-service:latest
    restart: always
    container_name: probank-message-service-instance
    networks: 
      - probank-network
    ports:
      - 9094:9094
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-MESSAGE-SERVICE
      SPRING_RABBITMQ_HOST: probank-rabbitmq
    healthcheck:
      test: "curl --fail --silent localhost:9094/actuator/health/readiness | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    depends_on:
      probank-rabbitmq:
        condition: service_healthy

  probank-apigateway:
    build: probank-apigateway/
    image: r15priyanshu/probank-apigateway:latest
    restart: always
    container_name: probank-apigateway-instance
    networks: 
      - probank-network
    ports:
      - 9090:9090
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: PROBANK-APIGATEWAY
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://probank-eurekaserver:8761/eureka/
    depends_on:
      probank-accounts-service:
        condition: service_healthy
      probank-loans-service:
        condition: service_healthy
      probank-cards-service:
        condition: service_healthy