#Defining All Services
services:
  probank-configserver:  #name that can be reffered inside this file
    build: probank-configserver/ #Will try to find Dockerfile in this location
    image: r15priyanshu/probank-configserver:latest
    restart: always
    container_name: probank-configserver-instance
    networks: 
      - probank-network
    ports:
      - 8888:8888
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_APPLICATION_NAME: CONFIG-SERVER
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 60s #perform retries in the interval of mentioned time
      timeout: 30s #wait only for mentioned time for the response
      retries: 2 #perform mentioned times retry in case of failure
      start_period: 30s #start health check after mentioned time


  probank-accounts-service:
    build: probank-accounts-service/ 
    image: r15priyanshu/probank-accounts-service:latest
    restart: always
    container_name: probank-accounts-service-instance
    networks: 
      - probank-network
    ports:
      - 9091:9091
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: ACCOUNTS-SERVICE
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
      probank-configserver:
        condition: service_healthy
    

  probank-loans-service:
    build: probank-loans-service/ 
    image: r15priyanshu/probank-loans-service:latest
    restart: always
    container_name: probank-loans-service-instance
    networks: 
      - probank-network
    ports:
      - 9092:9092
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: LOANS-SERVICE
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
    depends_on:
      probank-configserver:
        condition: service_healthy
   
      
  probank-cards-service:
    build: probank-cards-service/
    image: r15priyanshu/probank-cards-service:latest
    restart: always
    container_name: probank-cards-service-instance
    networks: 
      - probank-network
    ports:
      - 9093:9093
    environment:
      SPRING_PROFILES_ACTIVE: prd
      SPRING_APPLICATION_NAME: CARDS-SERVICE
      SPRING_CONFIG_IMPORT: configserver:http://probank-configserver:8888/
    depends_on:
      probank-configserver:
        condition: service_healthy


#Defining Custom Network
networks:
  probank-network:
    name: probank-network
    driver: bridge
